### ISSUE TITLE
Weekly Schedule not working standalone without framework

### ISSUE THREAD

**Issue by adrianrhodes** [CodyHouse/cd-weekly-schedule-changelog#1]
I moved the html file to the root directory and attached the files as required in the order specified.
However the weekly schedule does not show properly.
The times do not appear and the items all appear in one row from left to right.

**Comment by adrianrhodes** [comment]
Solved > the download is missing the file _3_weekly-schedule-init.js
Please add to download

**Comment by claudia-romano** [comment]
Hi Adrian, we do not intialize the component in the JS file. This way you can include your custom `searchData` function. You can find more details on the component Info:
https://codyhouse.co/ds/components/info/weekly-schedule
